### ISSUE TITLE
builtin functions aren't completed if a part of it is already typed

### ISSUE THREAD

**Issue by nycex** [SuperAuguste/zls#1] opened 2020-05-02 14:21 UTC
As I already said in discord, I added zls as lsp and it get's called but I have neither completion for builtin functions nor for global variables. This might just as well be a misconfiguration on my side, but it could also be a zls bug. [Here](https://codeberg.org/nycex/dotfiles/src/commit/ac008737f64dfaa2797c7fa822d5be71656a848d/.config/nvim/init.vim) is my full vim config, and those are the significant parts:
```viml
let lsp_filetypes = [ 'rust', 'zig', 'c', 'cpp', 'go', 'java', 'kotlin', 'sh', 'zsh', 'vim', 'javascript', 'typescript', 'python' ]
```
```viml
Plug 'dense-analysis/ale', { 'for': lsp_filetypes }
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins', 'for': lsp_filetypes }
```
```viml
let g:ale_linters = {
			\ 'rust': ['analyzer', 'clippy', 'rustfmt'],
			\ 'zig': ['zls'],
			\ 'python': ['pyls'],
			\ 'go': ['gopls'],
			\ 'javascript': ['tsserver', 'flow', 'eslint'],
			\ 'typescript': ['tsserver', 'eslint'],
			\ }

```
```viml
function! GetCommand(buffer) abort
	return '%e'
endfunction

function! GetZigProjectRoot(buffer) abort
	let l:cargo_file = ale#path#FindNearestFile(a:buffer, 'build.zig')

	return !empty(l:cargo_file) ? fnamemodify(l:cargo_file, ':h') : getcwd()
endfunction
```
```viml
call ale#linter#Define('zig', {
			\   'name': 'zls',
			\   'lsp': 'stdio',
			\   'executable': '/usr/bin/zls',
			\   'command': function('GetCommand'),
			\   'project_root': function('GetZigProjectRoot'),
			\})
```

**Comment by SuperAuguste** [comment] 2020-05-02 16:25
Hey nycex, in all honesty, I have never used Vim before. I don't see any apparent problems in your config, but again, I don't really use ale and deoplete. Could you somehow output an error log and check for any Vim runtime errors?

**Comment by nycex** [comment] 2020-05-02 16:51
I don't have any runtime errors, but I can say that errors in the file are shown, just the completion isn't working for me. I'll look into ale and deoplete, maybe there is a mode that shows some debug info.

**Comment by nycex** [comment] 2020-05-07 16:14
So I tried a few things and wasn't able to get any debug output besides the execution of zls itself. When trying with latest master though, I was able to get global variable and function completion, though builtins still don't work.

**Comment by alexnask** [comment] 2020-05-07 16:26
Werid, the builtin completion code sends the same kind of message as the global function completion code.

**Comment by SuperAuguste** [comment] 2020-05-07 16:30
> Weird, the builtin completion code sends the same kind of message as the global function completion code.

That's correct - both send a completion event, they just have different content.

**Comment by SuperAuguste** [comment] 2020-05-07 16:30
Maybe it's due to lack of snippet syntax support in ale/deoplete?

**Comment by SuperAuguste** [comment] 2020-05-07 16:42
This seems to indeed be the issue: https://github.com/dense-analysis/ale/issues/1821

**Comment by nycex** [comment] 2020-05-07 16:54
Yeah, that seems to be the case. I'll close this then.

**Comment by SuperAuguste** [comment] 2020-05-07 16:56
Very sorry about that @nycex! I'm gonna add a build option to disable snippets and render the plain versions of the builtins later, so you'll be able to use the language server. 😊

**Comment by nycex** [comment] 2020-05-07 17:07
You don't have to be sorry, it makes sense to add this as a snippet feature; it's not your fault my client doesn't support that 🙂. It'd be great if you could add it, as you already said, though 👍.

**Comment by SuperAuguste** [comment] 2020-05-07 17:17
Nycex, you can now `zig build -Dno_snippets` to enable no_snippets mode, which as its name indicates, disables all snippets! Thanks for bringing this issue to our attention!

**Comment by nycex** [comment] 2020-05-07 17:58
It still doesn't work, though that might have to do with the `@` in front of the completion, deoplete seems to split that, e.g. typing `@s` gives me a completion list with std in it. Maybe this behaviour is changable, I'll look into it.

**Comment by alexnask** [comment] 2020-05-07 18:05
> Edit: this doesn't seem to be the problem, changing @breakpoint() to breakpoint() in the data files doesn't solve the issue.

The server still only sends the completion if the current character is '@' so I wouldn't expect simply changing the builtin name would fix this if the issue is deoplete's handling of '@'.  

Anyway, I will try to test this in some other LSP clients to see if this is a common issue or just deoplete's.

**Comment by nycex** [comment] 2020-05-07 19:06
If it helps, here I have the output and input of zls I can intercept when trying it first with a function and then with builtin functions: https://bpaste.net/DAOA (the first one is input, the second one output)

**Comment by nycex** [comment] 2020-05-07 19:16
I'm pretty sure it is a problem with the `main.zig:413` check, because if I add `or true` to it, it works, but now only builtin functions work and they are **also** getting completed if no `@` is in front of them. I'm not entirely sure if this is a zls problem or a problem with the way deoplete handles those separators.

**Comment by SuperAuguste** [comment] 2020-05-07 20:09
Yep! This will def. be fixed by the analysis engine! `char == '@'` is a superhacky placeholder. If you just type `@` and then press tab, it should work with the current setup.

**Comment by nycex** [comment] 2020-05-07 20:17
I know, but for some reason deoplete expects at least one character after an `@` to do completion. I guess I'll leave this open until the analysis is done as far as fixing this?

**Comment by SuperAuguste** [comment] 2020-05-08 03:05
Fixed! It should work now nycex!

**Comment by nycex** [comment] 2020-05-08 12:37
It does work now! 👍
Also with snippets enabled though - so I don't know if you want to keep the ability to disable them in 🤷.

**Closed** 2020-05-08 12:40 UTC
Labels: bug, vim
